/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 04-mar-2018 11:30:21 p.m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `ERP_cliente` CASCADE
;

DROP TABLE IF EXISTS `ERP_pedido_cabecera` CASCADE
;

DROP TABLE IF EXISTS `ERP_pedido_linea` CASCADE
;

DROP TABLE IF EXISTS `pedido_cabecera` CASCADE
;

DROP TABLE IF EXISTS `pedido_linea` CASCADE
;

DROP TABLE IF EXISTS `suscripcion` CASCADE
;

DROP TABLE IF EXISTS `usuario` CASCADE
;

DROP TABLE IF EXISTS `WP_productos` CASCADE
;

/* Create Tables */

CREATE TABLE `ERP_cliente`
(
	`cod_cliente` INT NOT NULL,
	`cliente` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_cliente` PRIMARY KEY (`cod_cliente` ASC)
)

;

CREATE TABLE `ERP_pedido_cabecera`
(
	`id_pedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`id_cliente` INT 	 NULL,
	`fecha_pedido` DATE NOT NULL,
	`total_pagar` DOUBLE 	 NULL,
	`codigo_guia` VARCHAR(50) 	 NULL,
	`codigo_COT` VARCHAR(50) 	 NULL,
	`usr_ult_modif` VARCHAR(50) NOT NULL,
	`fec_ult_modif` DATETIME 	 NULL,
	CONSTRAINT `PK_pedido` PRIMARY KEY (`id_pedido` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET latin1
COLLATE latin1_swedish_ci

;

CREATE TABLE `ERP_pedido_linea`
(
	`id_pedido` INT UNSIGNED NOT NULL,
	`renglon` SMALLINT UNSIGNED NOT NULL,
	`cod_producto` INT 	 NULL,
	`sku` VARCHAR(50) 	 NULL,
	`cantidad` INT 	 UNSIGNED NULL,
	`precio_unitario` DOUBLE 	 NULL,
	`precio_total` DOUBLE 	 NULL,
	`usr_ult_modif` VARCHAR(50) 	 NULL,
	`fec_ult_modif` DATETIME 	 NULL,
	CONSTRAINT `PK_ERP_pedido_linea` PRIMARY KEY (`id_pedido` ASC, `renglon` ASC)
)

;

CREATE TABLE `pedido_cabecera`
(
	`id_pedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`cod_cliente` INT NOT NULL,
	`fec_creacion` DATETIME NOT NULL,
	`chk_informado_erp` TINYINT 	 NULL,
	`chk_temporal` TINYINT 	 NULL,
	`usr_ult_modif` VARCHAR(50) 	 NULL,
	`fec_ult_modif` DATETIME 	 NULL,
	CONSTRAINT `PK_pedido_cabecera` PRIMARY KEY (`id_pedido` ASC)
)

;

CREATE TABLE `pedido_linea`
(
	`id_pedido` INT UNSIGNED NOT NULL,
	`renglon` SMALLINT UNSIGNED NOT NULL,
	`cod_producto` VARCHAR(50) NOT NULL,
	`sku` INT 	 UNSIGNED NULL,
	`cantidad` DOUBLE NOT NULL,
	`precio_unitario` DOUBLE NOT NULL,
	`precio_total` DOUBLE 	 NULL,
	`usr_ult_modif` VARCHAR(50) 	 NULL,
	`fec_ult_modif` DATETIME 	 NULL,
	CONSTRAINT `PK_pedido_linea` PRIMARY KEY (`id_pedido` ASC, `renglon` ASC)
)

;

CREATE TABLE `suscripcion`
(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`correo` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_suscripcion` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET latin1
COLLATE latin1_swedish_ci

;

CREATE TABLE `usuario`
(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(25) NOT NULL,
	`apellido` VARCHAR(25) NOT NULL,
	`mail` VARCHAR(25) NOT NULL,
	`password` VARCHAR(25) NOT NULL,
	CONSTRAINT `PK_usuario` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET latin1
COLLATE latin1_swedish_ci

;

CREATE TABLE `WP_productos`
(
	`cod_producto` INT NOT NULL,
	`sku` VARCHAR(15) NOT NULL,
	`titulo` VARCHAR(50) NOT NULL,
	`stock` INT UNSIGNED NOT NULL,
	`precio` FLOAT(8,3) NOT NULL,
	`rubro` VARCHAR(30) NOT NULL,
	`marca` VARCHAR(30) NOT NULL,
	`modelo` VARCHAR(30) NOT NULL,
	`talle` VARCHAR(4) NOT NULL,
	`destacado` TINYINT NOT NULL,
	`publicado` TINYINT NOT NULL,
	`img` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_productos` PRIMARY KEY (`cod_producto` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET latin1
COLLATE latin1_swedish_ci

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `ERP_cliente` 
 ADD INDEX `IXFK_ERP_cliente_ERP_pedido_cabecera` (`cod_cliente` ASC)
;

ALTER TABLE `ERP_pedido_cabecera` 
 ADD INDEX `IXFK_ERP_pedido_cabecera_ERP_cliente` (`id_cliente` ASC)
;

ALTER TABLE `ERP_pedido_cabecera` 
 ADD INDEX `IXFK_ERP_pedido_cabecera_ERP_pedido_linea` (`id_pedido` ASC)
;

ALTER TABLE `ERP_pedido_linea` 
 ADD INDEX `IXFK_ERP_pedido_linea_ERP_pedido_cabecera` (`id_pedido` ASC)
;

ALTER TABLE `ERP_pedido_linea` 
 ADD INDEX `IXFK_ERP_pedido_linea_WP_productos` (`cod_producto` ASC)
;

ALTER TABLE `pedido_cabecera` 
 ADD INDEX `IXFK_pedido_cabecera_cliente` (`cod_cliente` ASC)
;

ALTER TABLE `pedido_linea` 
 ADD INDEX `IXFK_pedido_linea_pedido_cabecera` (`id_pedido` ASC)
;

ALTER TABLE `suscripcion` 
 ADD CONSTRAINT `correo` UNIQUE (`correo` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `ERP_pedido_cabecera` 
 ADD CONSTRAINT `FK_ERP_pedido_cabecera_ERP_cliente`
	FOREIGN KEY (`id_cliente`) REFERENCES `ERP_cliente` (`cod_cliente`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `ERP_pedido_linea` 
 ADD CONSTRAINT `FK_ERP_pedido_linea_ERP_pedido_cabecera`
	FOREIGN KEY (`id_pedido`) REFERENCES `ERP_pedido_cabecera` (`id_pedido`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `ERP_pedido_linea` 
 ADD CONSTRAINT `FK_ERP_pedido_linea_WP_productos`
	FOREIGN KEY (`cod_producto`) REFERENCES `WP_productos` (`cod_producto`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pedido_cabecera` 
 ADD CONSTRAINT `FK_pedido_cabecera_cliente`
	FOREIGN KEY (`cod_cliente`) REFERENCES `ERP_cliente` (`cod_cliente`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `pedido_linea` 
 ADD CONSTRAINT `FK_pedido_linea_pedido_cabecera`
	FOREIGN KEY (`id_pedido`) REFERENCES `pedido_cabecera` (`id_pedido`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
